In [1]:
import numpy as np
import torch

In [2]:
## 리스트 1.1
# 중첩 list를 지정
t = torch.tensor([[1, 2], [3, 4.]])

In [3]:
# device를 지정하면 GPU에 텐서를 만들 수 있다
t = torch.tensor([[1, 2], [3, 4.]], device="cuda:0")

AssertionError: Torch not compiled with CUDA enabled

In [4]:
# dtype을 사용해 데이터형을 지정하여 텐서를 만들 수 있다
t = torch.tensor([[1, 2], [3, 4.]], dtype=torch.float64)

In [5]:
# 0부터 9까지의 수치로 초기화된 1차원 텐서
t = torch.arange(0, 10)

In [6]:
# 모든 값이 0인 100 x 10의 텐서를
# 작성해서 to 메서드로 GPU에 전송
t = torch.zeros(100, 10).to("cuda:0")

AssertionError: Torch not compiled with CUDA enabled

In [7]:
# 정규 난수로 100 x 10의 텐서를 작성
t = torch.randn(100, 10)

In [8]:
# 텐서의 shape은 size 메서드로 확인 가능
t.size()

torch.Size([100, 10])

In [9]:
x = t.numpy()

In [10]:
print(x)

[[ 2.09464216e+00 -5.71704149e-01  3.80302727e-01 -9.24327791e-01
   7.52183259e-01 -5.56853712e-01  8.05037081e-01  3.56602341e-01
  -1.10157061e+00 -7.67340541e-01]
 [-2.52507985e-01  1.48965836e+00  3.37387323e-01 -1.62412322e+00
  -1.36263087e-01  5.47032714e-01  3.83772026e-03  5.31725228e-01
   6.63079858e-01 -5.07907927e-01]
 [ 4.74956930e-01  1.12819040e+00  9.51338559e-02 -2.54485607e-01
   9.01191652e-01 -2.08578587e+00  1.09547520e+00 -3.35594058e-01
  -1.56293321e+00 -7.41027236e-01]
 [-1.12004325e-01  1.00274158e+00 -3.91971707e-01  1.67644155e+00
  -5.41011333e-01 -7.23130107e-01  9.09916401e-01 -8.74294877e-01
  -4.17322852e-04  2.28790730e-01]
 [ 1.33711946e+00 -1.39516890e+00 -3.64364713e-01  6.09320223e-01
  -6.11701757e-02  1.50430310e+00  8.15007806e-01  4.76941973e-01
   3.75693738e-02  1.07823992e-02]
 [ 1.35117376e+00  6.28831163e-02 -2.16183648e-01 -1.38358438e+00
   2.90263712e-01  3.22747707e-01  4.33058292e-01  4.87266630e-01
   3.65068763e-02  7.01846778e-01

In [14]:
t = torch.tensor([[1,2,3], [4,5,6.]])
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [12]:
# 스칼라 첨자 지정 (row, column)
t[0, 2]

tensor(3.)

In [13]:
# 슬라이스로 지정
t[:, :2]

tensor([[1., 2.],
        [4., 5.]])

In [15]:
# 리스트로 지정
t[:, [1,2]]

tensor([[2., 3.],
        [5., 6.]])

In [16]:
# 마스크 배열을 사용해서 3보다 큰 부분만 선택
t[t > 3]

tensor([4., 5., 6.])

In [18]:
# [0, 1]의 요소를 100으로 설정
t[0, 1] = 100
print(t)

tensor([[  1., 100.,   3.],
        [  4.,   5.,   6.]])


In [19]:
# 슬라이스를 사용한 일괄 대입
t[:, 1] = 200
print(t)

tensor([[  1., 200.,   3.],
        [  4., 200.,   6.]])


In [20]:
# 마스크 배열을 사용해서 특정 조건의 요소만 치환
t[t > 10] = 20
print(t)

tensor([[ 1., 20.,  3.],
        [ 4., 20.,  6.]])
