<a href="https://colab.research.google.com/github/kevink1103/pytorch_rookie/blob/master/Chapter1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import torch

In [0]:
## 리스트 1.1 - 텐서 생성 예

In [0]:
# 중첩 list를 지정
t = torch.tensor([[1, 2], [3, 4.]])

In [0]:
# device를 지정하면 GPU에 텐서를 만들 수 있다
t = torch.tensor([[1, 2], [3, 4.]], device="cuda:0")

In [0]:
# dtype을 사용해 데이터형을 지정하여 텐서를 만들 수 있다
t = torch.tensor([[1, 2], [3, 4.]], dtype=torch.float64)

In [0]:
# 0부터 9까지의 수치로 초기화된 1차원 텐서
t = torch.arange(0, 10)

In [0]:
# 모든 값이 0인 100 x 10의 텐서를
# 작성해서 to 메서드로 GPU에 전송
t = torch.zeros(100, 10).to("cuda:0")

In [0]:
# 정규 난수로 100 x 10의 텐서를 작성
t = torch.randn(100, 10)

In [9]:
# 텐서의 shape은 size 메서드로 확인 가능
t.size()

torch.Size([100, 10])

In [0]:
## 리스트 1.2 - 텐서 변환 예

In [0]:
# numpy 메서드를 사용해 ndarray로 변환
t = torch.tensor([[1,2], [3,4.]])
x = t.numpy()

In [0]:
# GPU상의 텐서는 to 메서드로,
# CPU의 텐서로 이동(변환)할 필요가 있다
t = torch.tensor([[1,2], [3,4.]], device="cuda:0")
x = t.to("cpu").numpy()

In [13]:
print(t)
print(x)

tensor([[1., 2.],
        [3., 4.]], device='cuda:0')
[[1. 2.]
 [3. 4.]]


In [0]:
## 리스트 1.3 - 텐서의 인덱스 조작 예

In [15]:
t = torch.tensor([[1,2,3], [4,5,6.]])
print(t)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [16]:
# 스칼라 첨자 지정 (row, column)
t[0, 2]

tensor(3.)

In [17]:
# 슬라이스로 지정
t[:, :2]

tensor([[1., 2.],
        [4., 5.]])

In [18]:
# 리스트로 지정
t[:, [1,2]]

tensor([[2., 3.],
        [5., 6.]])

In [19]:
# 마스크 배열을 사용해서 3보다 큰 부분만 선택
t[t > 3]

tensor([4., 5., 6.])

In [20]:
# [0, 1]의 요소를 100으로 설정
t[0, 1] = 100
print(t)

tensor([[  1., 100.,   3.],
        [  4.,   5.,   6.]])


In [21]:
# 슬라이스를 사용한 일괄 대입
t[:, 1] = 200
print(t)

tensor([[  1., 200.,   3.],
        [  4., 200.,   6.]])


In [22]:
# 마스크 배열을 사용해서 특정 조건의 요소만 치환
t[t > 10] = 20
print(t)

tensor([[ 1., 20.,  3.],
        [ 4., 20.,  6.]])


In [0]:
## 리스트 1.4 - 텐서 연산

In [24]:
# 길이 3인 벡터
v = torch.tensor([1, 2, 3.])
w = torch.tensor([0, 10, 20.])
# 2 x 3의 행렬
m = torch.tensor([[0, 1, 2], [100, 200, 300.]])
print(v)
print(w)
print(m)

tensor([1., 2., 3.])
tensor([ 0., 10., 20.])
tensor([[  0.,   1.,   2.],
        [100., 200., 300.]])


In [25]:
# 벡터와 스칼라의 덧셈
v2 = v + 10
print(v2)

tensor([11., 12., 13.])


In [26]:
# 제곱도 같은 방식
v2 = v ** 2
print(v2)

tensor([1., 4., 9.])


In [27]:
# 동일 길이의 벡터 간 뺄쎔
z = v - w
print(z)

tensor([  1.,  -8., -17.])


In [28]:
# 여러가지 조합
u = 2 * v - w / 10 + 6.0
print(u)

tensor([ 8.,  9., 10.])


In [29]:
# 행렬과 스칼라
m2 = m * 2.0
print(m2)

tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])


In [30]:
# 행렬과 벡터
# (2, 3)인 행렬과 (3,)인 벡터이므로 브로드캐스트가 작동
m3 = m + v
print(m3)

tensor([[  1.,   3.,   5.],
        [101., 202., 303.]])


In [31]:
# 행렬 간 처리
m4 = m + m
print(m4)

tensor([[  0.,   2.,   4.],
        [200., 400., 600.]])


In [0]:
## 리스트 1.5 - 수학 함수

In [0]:
# 100 x 10의 테스트 데이터 생성
X = torch.randn(100, 10)

In [0]:
# 수학 함수를 표함하는 수식
Y = X * 2 + torch.abs(X)

In [0]:
# 평균치 구하기
m = torch.mean(X)

In [36]:
# 함수가 아닌 메서드로도 사용할 수 있다
m = X.mean()
print(m)

tensor(-0.0334)


In [37]:
# 집계 결과는 0차원의 텐서로 item 메서드를 사용해서
# 값을 추출할 수 있다
m_value = m.item()
print(m_value)

-0.033428650349378586


In [38]:
# 집계는 차원을 지정할 수도 있다. 다음은 행 방향으로 집계해서, (size=10)
# 열 단위로 평균값을 계산한다
m2 = X.mean(0)
print(m2)
m2.size()

tensor([ 0.0159, -0.1726,  0.1002, -0.1320, -0.2214, -0.0115,  0.1511, -0.1086,
         0.0472, -0.0026])


torch.Size([10])

In [0]:
## 리스트 1.6 - 텐서의 인덱스 조작 예

In [40]:
x1 = torch.tensor([[1, 2], [3, 4.]]) # 2x2
x2 = torch.tensor([[10, 20, 30], [40, 50, 60.]]) # 2x3
print(x1)
print(x2)

tensor([[1., 2.],
        [3., 4.]])
tensor([[10., 20., 30.],
        [40., 50., 60.]])


In [41]:
# 2x2를 4x1로 보여 준다
x1.view(4, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.]])

In [42]:
# -1은 표현할 수 있는 자동화된 값으로 대체되며, 한 번만 사용할 수 있다
# 아래 예에선 -1을 사용하면 자동으로 4가 된다
x1.view(1, -1)

tensor([[1., 2., 3., 4.]])

In [43]:
# 2x3을 전치해서 3x2로 만든다 (transform)
x2.t()

tensor([[10., 40.],
        [20., 50.],
        [30., 60.]])

In [44]:
# dim=1로 결합하면 2x5의 텐서를 만든다 (옆으로 append 개념)
torch.cat([x1, x2], dim=1)

tensor([[ 1.,  2., 10., 20., 30.],
        [ 3.,  4., 40., 50., 60.]])

In [45]:
# HWC을 CHW로 변환
# 64x32x3의 데이터가 100개
hwc_img_data = torch.rand(100, 64, 32, 3)
chw_img_data = hwc_img_data.transpose(1, 2).transpose(1, 3)
print(hwc_img_data[0, 0, 0])
print(chw_img_data[0, 0, 0])

tensor([0.6318, 0.1746, 0.3041])
tensor([0.6318, 0.8379, 0.1307, 0.9660, 0.2934, 0.8552, 0.2744, 0.8204, 0.1537,
        0.2456, 0.3040, 0.9100, 0.1645, 0.5841, 0.7064, 0.3908, 0.2777, 0.0330,
        0.5359, 0.5258, 0.3688, 0.7306, 0.4195, 0.5950, 0.2150, 0.7657, 0.5590,
        0.9296, 0.6705, 0.5054, 0.6835, 0.8227])


In [0]:
## 리스트 1.7 - 연산 예

In [0]:
m = torch.randn(100, 10)
v = torch.randn(10)

In [48]:
# 내적 (inner product)
d = torch.dot(v, v)
print(d)

tensor(7.6044)


In [49]:
# 100 x 1의 행렬과 길이 10인 벡터의 곱
# 결과는 길이 100인 벡터
v2 = torch.mv(m, v)
v2.size()

torch.Size([100])

In [50]:
# 행렬곱
m2 = torch.mm(m.t(), m)
m2.size()

torch.Size([10, 10])

In [0]:
# 특이값 분해
u, s, v = torch.svd(m)

In [0]:
## 리스트 1.8 - 자동 미분

In [0]:
x = torch.randn(100, 3)

In [0]:
# 미분의 변수로 사용하는 경우는 requires_grad를 True로 설정
a = torch.tensor([1, 2, 3.], requires_grad=True)

In [55]:
# 계산을 통해 자동으로 계산 그래프가 구축된다
y = torch.mv(x, a)
o = y.sum()
print(y)
print(o)

tensor([-6.8013, -3.4632, -4.5261,  7.2196, -1.5900, -2.4547, -3.0824, -3.3068,
         1.0234, -2.7066,  2.4643,  3.6700,  1.6380,  1.6605,  0.7856, -0.5504,
        -1.8135,  0.0862,  2.9535,  3.7206,  1.5127, -1.4333, -5.0677, -6.2439,
         0.9836, -3.0425,  1.8312, -4.5304, -5.3677, -1.7623, -2.1612,  1.1250,
        -0.9094,  4.3815, -0.6966, -4.8338, -7.1755,  0.2377, -9.0428, -4.3937,
        -6.0135,  0.0707, -2.6256, -4.2861,  0.0533, -7.3896, -5.6651, -0.7197,
        -1.9948, -6.0549,  2.9733,  4.5000,  3.1499,  2.5948,  4.9057,  2.2717,
        -0.3339,  0.0418, -5.3493,  3.8864,  0.3506,  1.8040, -4.1397, -1.6330,
         2.5585,  3.0508,  5.1753, -4.5233, -3.5432, -1.4385, -2.3560,  0.9386,
         1.4186,  3.9406, -7.8539,  6.7889, -3.2861, -0.0976, -0.2002, -2.0236,
        -1.9032, -0.9510, -3.8714,  6.7330, -2.5541, -2.6081,  2.6657, -0.3022,
        -8.2697, -6.2191,  3.2821, -5.4248, -2.7364, -7.4457,  0.1878,  2.1110,
        -1.8329, -0.0740,  1.5835,  3.28

In [56]:
# 미분을 실행
o.backward()
print(o)

tensor(-97.0650, grad_fn=<SumBackward0>)


In [57]:
# 분석 답과 비교
a.grad != x.sum(0)

tensor([0, 0, 0], dtype=torch.uint8)

In [58]:
# x는 requires_grad가 False이므로 미분이 계산되지 않는다
x.grad is None

True